#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker tag self-eck-admin-ui judu01/self-eck-admin-ui:v20basicbeta6
docker push judu01/self-eck-admin-ui:v20basicbeta6